//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.24 at 11:25:34 AM CEST 
//


package ch.bfh.ti.projekt1.sokoban.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for level complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="level">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="row" type="{http://bfh.ch}row" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="startPosition" type="{http://bfh.ch}startPosition"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlRootElement(name = "level")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "level", propOrder = {
        "row",
        "name",
        "startPosition",
        "uuid"
})
public class Level {

    protected List<Row> row;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected StartPosition startPosition;

    /**
     * Gets the value of the row property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the row property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRow().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Row }
     */
    public List<Row> getRow() {
        if (row == null) {
            row = new ArrayList<Row>();
        }
        return this.row;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startPosition property.
     *
     * @return possible object is
     *         {@link StartPosition }
     */
    public StartPosition getStartPosition() {
        return startPosition;
    }

    /**
     * Sets the value of the startPosition property.
     *
     * @param value allowed object is
     *              {@link StartPosition }
     */
    public void setStartPosition(StartPosition value) {
        this.startPosition = value;
    }

    /**
     * Gets the value of the uuid property.
     *
     * @return possible object is
     *         {@link String }
     */
	public String getUuid() {
		return uuid;
	}

    /**
     * Sets the value of the uuid property.
     *
     * @param value allowed object is
     *              {@link String }
     */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

}
