//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.24 at 11:25:34 AM CEST 
//


package ch.bfh.ti.projekt1.sokoban.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.bfh.ti.projekt1.sokoban.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Level_QNAME = new QName("http://bfh.ch", "level");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.bfh.ti.projekt1.sokoban.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link StartPosition }
     * 
     */
    public StartPosition createStartPosition() {
        return new StartPosition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Level }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://bfh.ch", name = "level")
    public JAXBElement<Level> createLevel(Level value) {
        return new JAXBElement<Level>(_Level_QNAME, Level.class, null, value);
    }

}
